// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/lms/v1beta1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GetStudentsRequest struct {
}

func (m *GetStudentsRequest) Reset()         { *m = GetStudentsRequest{} }
func (m *GetStudentsRequest) String() string { return proto.CompactTextString(m) }
func (*GetStudentsRequest) ProtoMessage()    {}
func (*GetStudentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4aaac713669af5ad, []int{0}
}
func (m *GetStudentsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetStudentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetStudentsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetStudentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStudentsRequest.Merge(m, src)
}
func (m *GetStudentsRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetStudentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStudentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStudentsRequest proto.InternalMessageInfo

type GetStudentsResponse struct {
	Students []*Student `protobuf:"bytes,1,rep,name=students,proto3" json:"students,omitempty"`
}

func (m *GetStudentsResponse) Reset()         { *m = GetStudentsResponse{} }
func (m *GetStudentsResponse) String() string { return proto.CompactTextString(m) }
func (*GetStudentsResponse) ProtoMessage()    {}
func (*GetStudentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4aaac713669af5ad, []int{1}
}
func (m *GetStudentsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetStudentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetStudentsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetStudentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStudentsResponse.Merge(m, src)
}
func (m *GetStudentsResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetStudentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStudentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStudentsResponse proto.InternalMessageInfo

func (m *GetStudentsResponse) GetStudents() []*Student {
	if m != nil {
		return m.Students
	}
	return nil
}

type GetLeaveRequestsRequest struct {
}

func (m *GetLeaveRequestsRequest) Reset()         { *m = GetLeaveRequestsRequest{} }
func (m *GetLeaveRequestsRequest) String() string { return proto.CompactTextString(m) }
func (*GetLeaveRequestsRequest) ProtoMessage()    {}
func (*GetLeaveRequestsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4aaac713669af5ad, []int{2}
}
func (m *GetLeaveRequestsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetLeaveRequestsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetLeaveRequestsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetLeaveRequestsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLeaveRequestsRequest.Merge(m, src)
}
func (m *GetLeaveRequestsRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetLeaveRequestsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLeaveRequestsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLeaveRequestsRequest proto.InternalMessageInfo

type GetLeaveRequestsResponse struct {
	Leaverequests []*ApplyLeaveRequest `protobuf:"bytes,1,rep,name=leaverequests,proto3" json:"leaverequests,omitempty"`
}

func (m *GetLeaveRequestsResponse) Reset()         { *m = GetLeaveRequestsResponse{} }
func (m *GetLeaveRequestsResponse) String() string { return proto.CompactTextString(m) }
func (*GetLeaveRequestsResponse) ProtoMessage()    {}
func (*GetLeaveRequestsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4aaac713669af5ad, []int{3}
}
func (m *GetLeaveRequestsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetLeaveRequestsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetLeaveRequestsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetLeaveRequestsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLeaveRequestsResponse.Merge(m, src)
}
func (m *GetLeaveRequestsResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetLeaveRequestsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLeaveRequestsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetLeaveRequestsResponse proto.InternalMessageInfo

func (m *GetLeaveRequestsResponse) GetLeaverequests() []*ApplyLeaveRequest {
	if m != nil {
		return m.Leaverequests
	}
	return nil
}

type GetLeaveApprovedRequestsRequest struct {
}

func (m *GetLeaveApprovedRequestsRequest) Reset()         { *m = GetLeaveApprovedRequestsRequest{} }
func (m *GetLeaveApprovedRequestsRequest) String() string { return proto.CompactTextString(m) }
func (*GetLeaveApprovedRequestsRequest) ProtoMessage()    {}
func (*GetLeaveApprovedRequestsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4aaac713669af5ad, []int{4}
}
func (m *GetLeaveApprovedRequestsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetLeaveApprovedRequestsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetLeaveApprovedRequestsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetLeaveApprovedRequestsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLeaveApprovedRequestsRequest.Merge(m, src)
}
func (m *GetLeaveApprovedRequestsRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetLeaveApprovedRequestsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLeaveApprovedRequestsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLeaveApprovedRequestsRequest proto.InternalMessageInfo

type GetLeaveApprovedRequestsResponse struct {
	Leaverequests []*ApplyLeaveRequest `protobuf:"bytes,1,rep,name=leaverequests,proto3" json:"leaverequests,omitempty"`
}

func (m *GetLeaveApprovedRequestsResponse) Reset()         { *m = GetLeaveApprovedRequestsResponse{} }
func (m *GetLeaveApprovedRequestsResponse) String() string { return proto.CompactTextString(m) }
func (*GetLeaveApprovedRequestsResponse) ProtoMessage()    {}
func (*GetLeaveApprovedRequestsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4aaac713669af5ad, []int{5}
}
func (m *GetLeaveApprovedRequestsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetLeaveApprovedRequestsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetLeaveApprovedRequestsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetLeaveApprovedRequestsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLeaveApprovedRequestsResponse.Merge(m, src)
}
func (m *GetLeaveApprovedRequestsResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetLeaveApprovedRequestsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLeaveApprovedRequestsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetLeaveApprovedRequestsResponse proto.InternalMessageInfo

func (m *GetLeaveApprovedRequestsResponse) GetLeaverequests() []*ApplyLeaveRequest {
	if m != nil {
		return m.Leaverequests
	}
	return nil
}

type GetLeaveStatusResponse struct {
	Leaverequest *ApplyLeaveRequest `protobuf:"bytes,1,opt,name=leaverequest,proto3" json:"leaverequest,omitempty"`
}

func (m *GetLeaveStatusResponse) Reset()         { *m = GetLeaveStatusResponse{} }
func (m *GetLeaveStatusResponse) String() string { return proto.CompactTextString(m) }
func (*GetLeaveStatusResponse) ProtoMessage()    {}
func (*GetLeaveStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4aaac713669af5ad, []int{6}
}
func (m *GetLeaveStatusResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetLeaveStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetLeaveStatusResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetLeaveStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLeaveStatusResponse.Merge(m, src)
}
func (m *GetLeaveStatusResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetLeaveStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLeaveStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetLeaveStatusResponse proto.InternalMessageInfo

func (m *GetLeaveStatusResponse) GetLeaverequest() *ApplyLeaveRequest {
	if m != nil {
		return m.Leaverequest
	}
	return nil
}

type GetLeaveStatusRequest struct {
	LeaveID string `protobuf:"bytes,1,opt,name=leaveID,proto3" json:"leaveID,omitempty"`
}

func (m *GetLeaveStatusRequest) Reset()         { *m = GetLeaveStatusRequest{} }
func (m *GetLeaveStatusRequest) String() string { return proto.CompactTextString(m) }
func (*GetLeaveStatusRequest) ProtoMessage()    {}
func (*GetLeaveStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4aaac713669af5ad, []int{7}
}
func (m *GetLeaveStatusRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetLeaveStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetLeaveStatusRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetLeaveStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLeaveStatusRequest.Merge(m, src)
}
func (m *GetLeaveStatusRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetLeaveStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLeaveStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLeaveStatusRequest proto.InternalMessageInfo

func (m *GetLeaveStatusRequest) GetLeaveID() string {
	if m != nil {
		return m.LeaveID
	}
	return ""
}

func init() {
	proto.RegisterType((*GetStudentsRequest)(nil), "cosmos.lms.v1beta1.GetStudentsRequest")
	proto.RegisterType((*GetStudentsResponse)(nil), "cosmos.lms.v1beta1.GetStudentsResponse")
	proto.RegisterType((*GetLeaveRequestsRequest)(nil), "cosmos.lms.v1beta1.GetLeaveRequestsRequest")
	proto.RegisterType((*GetLeaveRequestsResponse)(nil), "cosmos.lms.v1beta1.GetLeaveRequestsResponse")
	proto.RegisterType((*GetLeaveApprovedRequestsRequest)(nil), "cosmos.lms.v1beta1.GetLeaveApprovedRequestsRequest")
	proto.RegisterType((*GetLeaveApprovedRequestsResponse)(nil), "cosmos.lms.v1beta1.GetLeaveApprovedRequestsResponse")
	proto.RegisterType((*GetLeaveStatusResponse)(nil), "cosmos.lms.v1beta1.GetLeaveStatusResponse")
	proto.RegisterType((*GetLeaveStatusRequest)(nil), "cosmos.lms.v1beta1.GetLeaveStatusRequest")
}

func init() { proto.RegisterFile("cosmos/lms/v1beta1/query.proto", fileDescriptor_4aaac713669af5ad) }

var fileDescriptor_4aaac713669af5ad = []byte{
	// 470 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x94, 0x4d, 0x6f, 0xd3, 0x30,
	0x1c, 0xc6, 0x6b, 0xde, 0xf9, 0x0f, 0x24, 0x64, 0xde, 0x42, 0xb6, 0xb9, 0x59, 0x44, 0x37, 0xde,
	0x94, 0xa8, 0x1b, 0x12, 0xe7, 0x21, 0xa4, 0x69, 0x02, 0x21, 0x91, 0xdd, 0xb8, 0x65, 0x9b, 0x15,
	0x4d, 0x4a, 0x63, 0x2f, 0x76, 0xaa, 0xf6, 0xca, 0x95, 0x0b, 0x52, 0x2f, 0x7c, 0x0f, 0xbe, 0x04,
	0xc7, 0x4a, 0x5c, 0x38, 0xa2, 0x96, 0x8f, 0xc1, 0x01, 0xd5, 0x76, 0xda, 0xa4, 0x4d, 0x4a, 0x39,
	0xec, 0x18, 0xff, 0x9f, 0xc7, 0xcf, 0xcf, 0xf1, 0x93, 0x00, 0x39, 0x61, 0xa2, 0xc3, 0x84, 0x1f,
	0x77, 0x84, 0xdf, 0x6d, 0x1f, 0x53, 0x19, 0xb6, 0xfd, 0xf3, 0x8c, 0xa6, 0x7d, 0x8f, 0xa7, 0x4c,
	0x32, 0x8c, 0xf5, 0xdc, 0x8b, 0x3b, 0xc2, 0x33, 0x73, 0x7b, 0xbd, 0xc2, 0x23, 0x7b, 0xda, 0x60,
	0x6f, 0x44, 0x8c, 0x45, 0x31, 0xf5, 0x43, 0x7e, 0xe6, 0x87, 0x49, 0xc2, 0x64, 0x28, 0xcf, 0x58,
	0x22, 0xf4, 0xd4, 0xbd, 0x07, 0xf8, 0x80, 0xca, 0x23, 0x99, 0x9d, 0xd2, 0x44, 0x8a, 0x80, 0x9e,
	0x67, 0x54, 0x48, 0xf7, 0x3d, 0xdc, 0x2d, 0xad, 0x0a, 0xce, 0x12, 0x41, 0xf1, 0x2b, 0xb8, 0x21,
	0xcc, 0x9a, 0x85, 0x9c, 0xcb, 0x4f, 0xd6, 0x76, 0xd7, 0xbd, 0x45, 0x1c, 0xcf, 0xf8, 0x82, 0xa9,
	0xd8, 0x7d, 0x04, 0x0f, 0x0f, 0xa8, 0x7c, 0x47, 0xc3, 0x2e, 0x35, 0x11, 0xd3, 0xa8, 0x08, 0xac,
	0xc5, 0x91, 0xc9, 0x7b, 0x0b, 0xb7, 0xe3, 0xc9, 0x20, 0x35, 0x03, 0x13, 0xda, 0xaa, 0x0a, 0xdd,
	0xe7, 0x3c, 0xee, 0x17, 0xb7, 0x09, 0xca, 0x5e, 0x77, 0x0b, 0x9a, 0x79, 0xd0, 0x3e, 0xe7, 0x29,
	0xeb, 0xd2, 0xd3, 0x79, 0x16, 0x06, 0x4e, 0xbd, 0xe4, 0x22, 0x98, 0x4e, 0xe0, 0x41, 0x1e, 0x78,
	0x24, 0x43, 0x99, 0xcd, 0x62, 0x0e, 0xe1, 0x56, 0x51, 0x6a, 0x21, 0x07, 0xad, 0x9e, 0x52, 0xb2,
	0xba, 0x6d, 0xb8, 0x3f, 0x1f, 0xa2, 0x06, 0xd8, 0x82, 0xeb, 0x4a, 0x78, 0xf8, 0x46, 0x6d, 0x7f,
	0x33, 0xc8, 0x1f, 0x77, 0xff, 0x5c, 0x81, 0xab, 0x1f, 0x26, 0xa5, 0xc3, 0x9f, 0x11, 0xdc, 0x29,
	0x54, 0x41, 0x2f, 0x6e, 0x57, 0x61, 0x2c, 0xd6, 0xc8, 0xde, 0xf9, 0xa7, 0x4e, 0x9f, 0xd6, 0xdd,
	0xfe, 0xf4, 0xe3, 0xf7, 0xe0, 0x92, 0x83, 0x89, 0x5f, 0xd1, 0xe4, 0x88, 0x4a, 0x53, 0x24, 0xfc,
	0x15, 0xcd, 0xce, 0x92, 0xdf, 0x8c, 0x46, 0x7a, 0x5e, 0x13, 0x55, 0xd5, 0x39, 0xfb, 0xc5, 0x6a,
	0x62, 0x03, 0xf7, 0x58, 0xc1, 0x11, 0xbc, 0x51, 0x03, 0xa7, 0x5e, 0x1a, 0xfe, 0x86, 0x60, 0xb3,
	0xae, 0x3c, 0x1a, 0x71, 0x6f, 0x59, 0x6a, 0x4d, 0x25, 0xed, 0x97, 0xff, 0x67, 0x32, 0xc8, 0x3b,
	0x0a, 0x79, 0x0b, 0x37, 0x6b, 0x90, 0x43, 0x63, 0xc4, 0x03, 0xa4, 0xbe, 0xf4, 0x42, 0x39, 0x34,
	0xeb, 0xd3, 0x65, 0xb1, 0xa5, 0x16, 0xd9, 0xcf, 0x56, 0x91, 0x1a, 0xae, 0x96, 0xe2, 0x6a, 0xe2,
	0xcd, 0xda, 0x7b, 0x9e, 0xc8, 0x5f, 0xb7, 0xbe, 0x8f, 0x08, 0x1a, 0x8e, 0x08, 0xfa, 0x35, 0x22,
	0xe8, 0xcb, 0x98, 0x34, 0x86, 0x63, 0xd2, 0xf8, 0x39, 0x26, 0x8d, 0x8f, 0x6b, 0x3d, 0x65, 0x91,
	0x7d, 0x4e, 0xc5, 0xf1, 0x35, 0xf5, 0x0b, 0xdb, 0xfb, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xfe, 0xc0,
	0x3b, 0x1a, 0x33, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	GetStudentsQuery(ctx context.Context, in *GetStudentsRequest, opts ...grpc.CallOption) (*GetStudentsResponse, error)
	GetLeaveRequestsQuery(ctx context.Context, in *GetLeaveRequestsRequest, opts ...grpc.CallOption) (*GetLeaveRequestsResponse, error)
	GetLeaveApprovedRequestsQuery(ctx context.Context, in *GetLeaveApprovedRequestsRequest, opts ...grpc.CallOption) (*GetLeaveApprovedRequestsResponse, error)
	GetLeaveStatusQuery(ctx context.Context, in *GetLeaveStatusRequest, opts ...grpc.CallOption) (*GetLeaveStatusResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) GetStudentsQuery(ctx context.Context, in *GetStudentsRequest, opts ...grpc.CallOption) (*GetStudentsResponse, error) {
	out := new(GetStudentsResponse)
	err := c.cc.Invoke(ctx, "/cosmos.lms.v1beta1.Query/GetStudentsQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetLeaveRequestsQuery(ctx context.Context, in *GetLeaveRequestsRequest, opts ...grpc.CallOption) (*GetLeaveRequestsResponse, error) {
	out := new(GetLeaveRequestsResponse)
	err := c.cc.Invoke(ctx, "/cosmos.lms.v1beta1.Query/GetLeaveRequestsQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetLeaveApprovedRequestsQuery(ctx context.Context, in *GetLeaveApprovedRequestsRequest, opts ...grpc.CallOption) (*GetLeaveApprovedRequestsResponse, error) {
	out := new(GetLeaveApprovedRequestsResponse)
	err := c.cc.Invoke(ctx, "/cosmos.lms.v1beta1.Query/GetLeaveApprovedRequestsQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetLeaveStatusQuery(ctx context.Context, in *GetLeaveStatusRequest, opts ...grpc.CallOption) (*GetLeaveStatusResponse, error) {
	out := new(GetLeaveStatusResponse)
	err := c.cc.Invoke(ctx, "/cosmos.lms.v1beta1.Query/GetLeaveStatusQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	GetStudentsQuery(context.Context, *GetStudentsRequest) (*GetStudentsResponse, error)
	GetLeaveRequestsQuery(context.Context, *GetLeaveRequestsRequest) (*GetLeaveRequestsResponse, error)
	GetLeaveApprovedRequestsQuery(context.Context, *GetLeaveApprovedRequestsRequest) (*GetLeaveApprovedRequestsResponse, error)
	GetLeaveStatusQuery(context.Context, *GetLeaveStatusRequest) (*GetLeaveStatusResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) GetStudentsQuery(ctx context.Context, req *GetStudentsRequest) (*GetStudentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStudentsQuery not implemented")
}
func (*UnimplementedQueryServer) GetLeaveRequestsQuery(ctx context.Context, req *GetLeaveRequestsRequest) (*GetLeaveRequestsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLeaveRequestsQuery not implemented")
}
func (*UnimplementedQueryServer) GetLeaveApprovedRequestsQuery(ctx context.Context, req *GetLeaveApprovedRequestsRequest) (*GetLeaveApprovedRequestsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLeaveApprovedRequestsQuery not implemented")
}
func (*UnimplementedQueryServer) GetLeaveStatusQuery(ctx context.Context, req *GetLeaveStatusRequest) (*GetLeaveStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLeaveStatusQuery not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_GetStudentsQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStudentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetStudentsQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.lms.v1beta1.Query/GetStudentsQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetStudentsQuery(ctx, req.(*GetStudentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetLeaveRequestsQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLeaveRequestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetLeaveRequestsQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.lms.v1beta1.Query/GetLeaveRequestsQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetLeaveRequestsQuery(ctx, req.(*GetLeaveRequestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetLeaveApprovedRequestsQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLeaveApprovedRequestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetLeaveApprovedRequestsQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.lms.v1beta1.Query/GetLeaveApprovedRequestsQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetLeaveApprovedRequestsQuery(ctx, req.(*GetLeaveApprovedRequestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetLeaveStatusQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLeaveStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetLeaveStatusQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.lms.v1beta1.Query/GetLeaveStatusQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetLeaveStatusQuery(ctx, req.(*GetLeaveStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cosmos.lms.v1beta1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStudentsQuery",
			Handler:    _Query_GetStudentsQuery_Handler,
		},
		{
			MethodName: "GetLeaveRequestsQuery",
			Handler:    _Query_GetLeaveRequestsQuery_Handler,
		},
		{
			MethodName: "GetLeaveApprovedRequestsQuery",
			Handler:    _Query_GetLeaveApprovedRequestsQuery_Handler,
		},
		{
			MethodName: "GetLeaveStatusQuery",
			Handler:    _Query_GetLeaveStatusQuery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cosmos/lms/v1beta1/query.proto",
}

func (m *GetStudentsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetStudentsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetStudentsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *GetStudentsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetStudentsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetStudentsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Students) > 0 {
		for iNdEx := len(m.Students) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Students[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *GetLeaveRequestsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetLeaveRequestsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetLeaveRequestsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *GetLeaveRequestsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetLeaveRequestsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetLeaveRequestsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Leaverequests) > 0 {
		for iNdEx := len(m.Leaverequests) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Leaverequests[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *GetLeaveApprovedRequestsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetLeaveApprovedRequestsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetLeaveApprovedRequestsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *GetLeaveApprovedRequestsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetLeaveApprovedRequestsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetLeaveApprovedRequestsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Leaverequests) > 0 {
		for iNdEx := len(m.Leaverequests) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Leaverequests[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *GetLeaveStatusResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetLeaveStatusResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetLeaveStatusResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Leaverequest != nil {
		{
			size, err := m.Leaverequest.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetLeaveStatusRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetLeaveStatusRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetLeaveStatusRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.LeaveID) > 0 {
		i -= len(m.LeaveID)
		copy(dAtA[i:], m.LeaveID)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.LeaveID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GetStudentsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *GetStudentsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Students) > 0 {
		for _, e := range m.Students {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *GetLeaveRequestsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *GetLeaveRequestsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Leaverequests) > 0 {
		for _, e := range m.Leaverequests {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *GetLeaveApprovedRequestsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *GetLeaveApprovedRequestsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Leaverequests) > 0 {
		for _, e := range m.Leaverequests {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *GetLeaveStatusResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Leaverequest != nil {
		l = m.Leaverequest.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *GetLeaveStatusRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.LeaveID)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GetStudentsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetStudentsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetStudentsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetStudentsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetStudentsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetStudentsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Students", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Students = append(m.Students, &Student{})
			if err := m.Students[len(m.Students)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetLeaveRequestsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetLeaveRequestsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetLeaveRequestsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetLeaveRequestsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetLeaveRequestsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetLeaveRequestsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Leaverequests", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Leaverequests = append(m.Leaverequests, &ApplyLeaveRequest{})
			if err := m.Leaverequests[len(m.Leaverequests)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetLeaveApprovedRequestsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetLeaveApprovedRequestsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetLeaveApprovedRequestsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetLeaveApprovedRequestsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetLeaveApprovedRequestsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetLeaveApprovedRequestsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Leaverequests", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Leaverequests = append(m.Leaverequests, &ApplyLeaveRequest{})
			if err := m.Leaverequests[len(m.Leaverequests)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetLeaveStatusResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetLeaveStatusResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetLeaveStatusResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Leaverequest", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Leaverequest == nil {
				m.Leaverequest = &ApplyLeaveRequest{}
			}
			if err := m.Leaverequest.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetLeaveStatusRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetLeaveStatusRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetLeaveStatusRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LeaveID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LeaveID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
